// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2OeU2MaCnPBvxlvVCcV5214LdzC9XuIw',
    appId: '1:343904983445:web:eb241f4457298d2a66be9c',
    messagingSenderId: '343904983445',
    projectId: 'geolibackend',
    authDomain: 'geolibackend.firebaseapp.com',
    storageBucket: 'geolibackend.firebasestorage.app',
    measurementId: 'G-YYLK8Q9RBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVCsHy2CG9Kwh6jAxujK9Wvr2In1PFGKw',
    appId: '1:343904983445:android:4e51233192493d6566be9c',
    messagingSenderId: '343904983445',
    projectId: 'geolibackend',
    storageBucket: 'geolibackend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtcNtHw7W-rvvmknWR-42NHSOmmQ9bEmo',
    appId: '1:343904983445:ios:838fa88d88eb510766be9c',
    messagingSenderId: '343904983445',
    projectId: 'geolibackend',
    storageBucket: 'geolibackend.firebasestorage.app',
    iosClientId: '343904983445-3bvvin2n9maiag48oh1gh23e39uqsajj.apps.googleusercontent.com',
    iosBundleId: 'com.example.geoli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtcNtHw7W-rvvmknWR-42NHSOmmQ9bEmo',
    appId: '1:343904983445:ios:838fa88d88eb510766be9c',
    messagingSenderId: '343904983445',
    projectId: 'geolibackend',
    storageBucket: 'geolibackend.firebasestorage.app',
    iosClientId: '343904983445-3bvvin2n9maiag48oh1gh23e39uqsajj.apps.googleusercontent.com',
    iosBundleId: 'com.example.geoli',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2OeU2MaCnPBvxlvVCcV5214LdzC9XuIw',
    appId: '1:343904983445:web:2e3d2c76b2fc278766be9c',
    messagingSenderId: '343904983445',
    projectId: 'geolibackend',
    authDomain: 'geolibackend.firebaseapp.com',
    storageBucket: 'geolibackend.firebasestorage.app',
    measurementId: 'G-TSKC6GM4X4',
  );
}
